### ISSUE TITLE
html-api-links

### ISSUE THREAD

**Issue by Allen-EC** [Allen-EC/workout_kitchen#1]
# HTML API Links.

## User Story
The app will require the use of a number of APIs.
These APIs will need to be linked into the application.

## Acceptance Criteria
GIVEN a list of APIs used in the application,
WHEN the application is loaded,
THEN all necessary API links will be successfully loaded.

**Comment by Bh00fie** [comment]
#2 
Added basic structure to HTML file, links to local "script.js" and "style.css" files as well as various APIs and Libraries such as PopperJS, Bootstrap, jQuery and jQuery UI.
