### ISSUE TITLE
Place needed images to images folder

### ISSUE THREAD

**Issue by 1Eva1987** [Allen-EC/workout_kitchen#3]
## User story:

As a member of the project,
I want to add needed images to images folder ,
so they could be easily accessible to all project participants

## Acceptance Criteria

GIVEN a workout_kitchen folders
WHEN I open images folder
THEN I can see images that will be used in the project

**Comment by 1Eva1987** [comment]
pixa bay
pexels

**Comment by codenamehaylz** [comment]
Unsplash is also good for free images

**Comment by Bh00fie** [comment]
https://pixabay.com/ : Pixabay
https://www.pexels.com/ : Pexels
https://www.google.co.uk/imghp?hl=en&authuser=0&ogbl : Google Images
https://www.midjourney.com/ : Creating Images using AI (discord)
https://www.foodiesfeed.com/ : foodiesfeed
https://unsplash.com/ : unsplash

Most of these links can be used to find images, if food is mentioned in the title, that website has just food photos

**Comment by codenamehaylz** [comment]
https://pixabay.com/photos/meat-dumbbell-cucumber-pepper-food-3183070/
https://pixabay.com/photos/fitness-dumbbell-vegetables-3168246/
https://pixabay.com/photos/meat-dumbbells-food-muscles-3183069/

**Comment by Bh00fie** [comment]
For placeholder: https://placeholder.com/
